Writable:
  LogLevel: INFO
Service:
  Host: "localhost"
  Port: 61805
  StartupMsg: "OpenVINO OVMS device service started"

Device:
  # These have common values (currently), but must be here for service local env overrides to apply when customized
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"
